### PR TITLE
Fix bug regarding crash on exit and excessive logging

### PR DESCRIPTION
**Pull request by mfussi66**
Fixes https://github.com/robotology/yarp-device-ultrapython/issues/12

### CODE REVIEW

**Comment by pattacini** [comment]
My warm advice is that you rebase your fork on the upstream master, @mfussi66.
I can see too many commits that are dated back in time, indeed.

**Comment by pattacini** [comment]
Just seen that the rebase perfectly worked 🚀

**Comment by pattacini** [comment]
cc @mfussi66 @triccyx

**Comment by mfussi66** [comment]
As far as I know, regarding the 3 points in the issue: 
1. The application crash on exit was corrected 
2. The excessive logging cannot really be fixed completely: since yarp does not provide flags to suppress all logging, warnings and errors will still be printed at minimum (https://github.com/robotology/yarp-device-ultrapython/issues/12#issuecomment-893575988). After all, I assume printing errors (eg no device found) is relevant.
3. Fixed in the PR!

**Comment by pattacini** [comment]
Thanks @mfussi66 👍🏻 
So I think we could integrate already this PR.
@triccyx, it's your turn now.

**Review by triccyx — APPROVED** [review]

**Pull request merged**
