### PR TITLE
Add Contrast control to GUI

### PR DESCRIPTION
**Pull request by mfussi66**
This pull request involves the addition of contrast control for the Ultrapython cameras, by means of the sliders in the GUI.

### CODE REVIEW

**Comment by pattacini** [comment]
Why is this PR closed?

**Comment by pattacini** [comment]
Just reopened.

**Comment by pattacini** [comment]
If you want to change the base and the compare branches, just edit it.

**Comment by pattacini** [comment]
Ok, I've seen that you opened up a new PR!
Actually there was no need for that.

**Comment by mfussi66** [comment]
Sorry about that, I closed it because I could not find a way to change my branch from `dev` to `master`, and I had to create a new one.

**Comment by pattacini** [comment]
Never mind!
There's an <kbd>Edit</kbd> button in the upper right corner of the PR dashboard.

**Pull request closed without merging**
